spring:
  security:
    jwt:
      key: abcdefjhijk
      expire: 7
    filter:
      order: -100

  datasource:
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study